// errors
export const M_LIMIT_EXCEEDED = 'M_LIMIT_EXCEEDED';
export const M_MISSING_TOKEN = 'M_MISSING_TOKEN';
export const M_UNKNOWN_TOKEN = 'M_UNKNOWN_TOKEN';
export const M_FORBIDDEN = 'M_FORBIDDEN';
export const M_BAD_JSON = 'M_BAD_JSON';
export const M_NOT_JSON = 'M_NOT_JSON';
export const M_UNKNOWN = 'M_UNKNOWN';
export const M_UNRECOGNIZED = 'M_UNRECOGNIZED';
export const M_UNAUTHORIZED = 'M_UNAUTHORIZED';
export const M_USER_DEACTIVATED = 'M_USER_DEACTIVATED';
export const M_USER_IN_USE = 'M_USER_IN_USE';
export const M_INVALID_USERNAME = 'M_INVALID_USERNAME';
export const M_ROOM_IN_USE = 'M_ROOM_IN_USE';
export const M_INVALID_ROOM_STATE = 'M_INVALID_ROOM_STATE';
export const M_THREEPID_IN_USE = 'M_THREEPID_IN_USE';
export const M_THREEPID_NOT_FOUND = 'M_THREEPID_NOT_FOUND';
export const M_THREEPID_AUTH_FAILED = 'M_THREEPID_AUTH_FAILED';
export const M_THREEPID_DENIED = 'M_THREEPID_DENIED';
export const M_SERVER_NOT_TRUSTED = 'M_SERVER_NOT_TRUSTED';
export const M_UNSUPPORTED_ROOM_VERSION = 'M_UNSUPPORTED_ROOM_VERSION';
export const M_INCOMPATIBLE_ROOM_VERSION = 'M_INCOMPATIBLE_ROOM_VERSION';
export const M_BAD_STATE = 'M_BAD_STATE';
export const M_GUEST_ACCESS_FORBIDDEN = 'M_GUEST_ACCESS_FORBIDDEN';
export const M_CAPTCHA_NEEDED = 'M_CAPTCHA_NEEDED';
export const M_CAPTCHA_INVALID = 'M_CAPTCHA_INVALID';
export const M_MISSING_PARAM = 'M_MISSING_PARAM';
export const M_INVALID_PARAM = 'M_INVALID_PARAM';
export const M_TOO_LARGE = 'M_TOO_LARGE';
export const M_EXCLUSIVE = 'M_EXCLUSIVE';
export const M_RESOURCE_LIMIT_EXCEEDED = 'M_RESOURCE_LIMIT_EXCEEDED';
export const M_CANNOT_LEAVE_SERVER_NOTICE_ROOM =
    'M_CANNOT_LEAVE_SERVER_NOTICE_ROOM';

// authentication
export const M_LOGIN_PASSWORD = 'm.login.password';
